# Generated by Django 3.2.7 on 2021-09-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allbids', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersmakingbids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256)),
                ('on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentson', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercommenting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
